DROP TABLE
IF EXISTS `t_user`;

DROP TABLE
IF EXISTS `t_role`;

DROP TABLE
IF EXISTS `t_resource`;

DROP TABLE
IF EXISTS `t_role_resource`;

DROP TABLE
IF EXISTS `t_project`;

DROP TABLE
IF EXISTS `t_data_module`;

DROP TABLE
IF EXISTS `t_data_column`;

DROP TABLE
IF EXISTS `t_data_row`;

DROP TABLE
IF EXISTS `t_flow`;

DROP TABLE
IF EXISTS `t_step`;

DROP TABLE
IF EXISTS `t_result`;

DROP TABLE
IF EXISTS `t_test`;

DROP TABLE
IF EXISTS `t_dataset`;

DROP TABLE
IF EXISTS `t_dataset_module`;

DROP TABLE
IF EXISTS `t_config`;

CREATE TABLE `t_user` (
	`uid` SMALLINT UNSIGNED AUTO_INCREMENT COMMENT '用户ID',
	`username` VARCHAR (16) NOT NULL COMMENT '用户名',
	`password` CHAR (60) NOT NULL COMMENT '密码',
	`nickname` VARCHAR (8) NOT NULL COMMENT '昵称',
	`enable` TINYINT NOT NULL COMMENT '是否启用',
	`last_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '密码最后修改时间',
	`rid` TINYINT UNSIGNED NOT NULL COMMENT '用户角色ID',
	PRIMARY KEY (`uid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '用户表';

CREATE TABLE `t_role` (
	`rid` TINYINT UNSIGNED AUTO_INCREMENT COMMENT '角色ID',
	`name` VARCHAR (16) NOT NULL COMMENT '角色名称',
	`description` VARCHAR (10) NOT NULL COMMENT '角色描述',
	PRIMARY KEY (`rid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '角色表';

CREATE TABLE `t_resource` (
	`rsid` SMALLINT UNSIGNED AUTO_INCREMENT COMMENT '资源ID',
	`method` VARCHAR (7) NOT NULL COMMENT '请求方法',
	`url` VARCHAR (50) NOT NULL COMMENT '资源URL表达式',
	PRIMARY KEY (`rsid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '资源表';

CREATE TABLE `t_role_resource` (
	`rid` TINYINT UNSIGNED NOT NULL COMMENT '角色ID',
	`rsid` SMALLINT UNSIGNED NOT NULL COMMENT '资源ID',
	PRIMARY KEY (`rid`, `rsid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '角色资源表';

CREATE TABLE `t_project` (
	`pid` TINYINT UNSIGNED AUTO_INCREMENT COMMENT '项目ID',
	`name` VARCHAR (15) NOT NULL COMMENT '项目名称',
	`description` VARCHAR (30) NOT NULL COMMENT '项目描述',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`creator_id` SMALLINT UNSIGNED NOT NULL COMMENT '创建者ID',
	PRIMARY KEY (`pid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '项目表';

CREATE TABLE `t_data_module` (
	`mid` SMALLINT UNSIGNED AUTO_INCREMENT COMMENT '模块ID',
	`name` VARCHAR (10) NOT NULL COMMENT '模块名',
	`pid` TINYINT UNSIGNED NOT NULL COMMENT '所属项目ID',
	`class_name` VARCHAR (50) COMMENT '关联测试类名(仅用于UI自动化)',
	PRIMARY KEY (`mid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '数据模块表';

CREATE TABLE `t_data_column` (
	`cid` SMALLINT UNSIGNED AUTO_INCREMENT COMMENT '列ID',
	`name` VARCHAR (10) NOT NULL COMMENT '列名',
	`mid` SMALLINT UNSIGNED NOT NULL COMMENT '所属模块名',
	PRIMARY KEY (`cid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '数据列（仅用于记录模块包含哪些列）';

CREATE TABLE `t_data_row` (
	`roid` INT UNSIGNED COMMENT '行ID(行号)',
	`mid` SMALLINT UNSIGNED NOT NULL COMMENT '所属模块ID',
	`vals` JSON NOT NULL COMMENT '{列名: 值}',
	PRIMARY KEY (`roid`, `mid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '数据行';

CREATE TABLE `t_flow` (
	`fid` INT UNSIGNED COMMENT '业务流ID',
	`service_id` INT NOT NULL COMMENT '接口信息ID',
	`init_script` VARCHAR (255) COMMENT '初始化脚本名',
	`mid` SMALLINT UNSIGNED NOT NULL COMMENT '关联数据模块ID',
	PRIMARY KEY (`fid`, `service_id`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '业务流(接口测试)表';

CREATE TABLE `t_step` (
	`service_id` INT NOT NULL COMMENT '接口信息ID',
	`result_path` VARCHAR (255) NOT NULL COMMENT '返回值jsonpath',
	`type` TINYINT UNSIGNED NOT NULL COMMENT '接口类型，1：被依赖接口，2：被测接口',
	`order_no` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '接口执行顺序',
	PRIMARY KEY (`service_id`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '业务流(接口测试)表';

CREATE TABLE `t_result` (
	`reid` INT UNSIGNED AUTO_INCREMENT COMMENT '结果ID',
	`tid` INT UNSIGNED NOT NULL COMMENT '所属测试ID',
	`status` TINYINT NOT NULL COMMENT '结果',
	`start_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
	`end_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '结束时间',
	`detail` JSON NOT NULL COMMENT '结果详情',
	`pic` TEXT COMMENT '错误截图',
	PRIMARY KEY (`reid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '测试结果表';

CREATE TABLE `t_test` (
	`tid` INT UNSIGNED AUTO_INCREMENT COMMENT '测试ID',
	`pid` TINYINT UNSIGNED NOT NULL COMMENT '所属项目ID',
	`finish` TINYINT NOT NULL COMMENT '是否执行完成',
	`name` VARCHAR (20) NOT NULL COMMENT '项目名称',
	`creator_id` SMALLINT UNSIGNED NOT NULL COMMENT '创建者ID',
	`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`dsid` SMALLINT UNSIGNED NOT NULL COMMENT '所用数据集合ID',
	PRIMARY KEY (`tid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '测试表';

CREATE TABLE `t_dataset` (
	`dsid` SMALLINT UNSIGNED AUTO_INCREMENT COMMENT '数据集合ID',
	`name` VARCHAR (20) NOT NULL COMMENT '数据集合名',
	PRIMARY KEY (`dsid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '数据集合';

CREATE TABLE `t_dataset_module` (
	`dsid` SMALLINT UNSIGNED NOT NULL COMMENT '数据集合ID',
	`mid` SMALLINT UNSIGNED NOT NULL COMMENT '模块ID',
	PRIMARY KEY (`dsid`, `mid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '数据集合模块关联表';

CREATE TABLE t_config (
	`cid` SMALLINT UNSIGNED AUTO_INCREMENT COMMENT '配置项ID',
	`pid` TINYINT UNSIGNED NOT NULL COMMENT '所属项目ID',
	`name` VARCHAR (20) NOT NULL COMMENT '配置项名称',
	`val` VARCHAR (20) NOT NULL COMMENT '配置项值',
	PRIMARY KEY (`cid`)
) DEFAULT CHARACTER
SET = utf8 COMMENT = '配置信息表';
